; Common settings for all environments
[env]
monitor_speed = 115200

; ESP32 environments
[env:devkit_c]
platform = espressif32
board = esp32dev
framework = arduino

; Include paths for ESP32
build_flags = 
    -Ilib
    -Ilib/esp-controls
    -Ilib/led
    -Ilib/motor
    -Ilib/nfc
    -Ilib/remotexy
    -Ilib/servo
    -Ilib/spi_comm
    -Ilib/wireless-com

; Include libraries for ESP32
lib_deps = 
    ESP32Servo
    RemoteXY
    fastled/FastLED
    MFRC522

; Individual ESP32 board environments
[env:controller_xy]
extends = env:devkit_c
build_src_filter = +<controller_xy.cpp>

[env:esp_calibration]
extends = env:devkit_c
build_src_filter = +<esp_calibration.cpp>

[env:esp_dam_elevator]
extends = env:devkit_c
build_src_filter = +<esp_dam_elevator.cpp>

[env:esp_dam_gripper]
extends = env:devkit_c
build_src_filter = +<esp_dam_gripper.cpp>

[env:esp_nuclear]
extends = env:devkit_c
build_src_filter = +<esp_nuclear.cpp>

[env:esp_solar]
extends = env:devkit_c
build_src_filter = +<esp_solar.cpp>
build_flags = 
    ${env:devkit_c.build_flags}
    -DNUM_LEDS=4

[env:esp_tx]
extends = env:devkit_c
build_src_filter = +<esp_tx.cpp>

[env:esp_windmill_elevator]
extends = env:devkit_c
build_src_filter = +<esp_windmill_elevator.cpp>

[env:esp_windmill_gripper]
extends = env:devkit_c
build_src_filter = +<esp_windmill_gripper.cpp>
build_flags = 
    ${env:devkit_c.build_flags}
    -DNUM_LEDS=3

[env:esp_windmill_storage]
extends = env:devkit_c
build_src_filter = +<esp_windmill_storage.cpp>