; Common settings for all environments
[env]
monitor_speed = 115200

; ESP32 environments
[env:bootcamp]
platform = espressif32
board = esp32dev
framework = arduino

; Include paths for ESP32
build_flags = 
    -Iinc
    -Ilib
    -Ilib/remote_xy

; Include libraries for ESP32
lib_deps = 
    ESP32Servo
    RemoteXY

build_src_filter = +<main.cpp>